import { describe, it, expect } from 'vitest';

/**
 * Tests for the generateLetterHtml function in document-generation.service.ts.
 *
 * Verifies:
 *   1. Produces a complete HTML document
 *   2. Letterhead contains company name
 *   3. Metadata (claim number, letter type, generated by) appears in output
 *   4. UPL disclaimer is present in the footer
 *   5. Markdown bold, headings, and bullets are converted correctly
 *   6. Tables are rendered as HTML tables
 *   7. Horizontal rules are rendered
 *   8. Print CSS is included
 */

import {
  generateLetterHtml,
} from '../../server/services/document-generation.service.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const METADATA = {
  claimNumber: 'WC-2026-0042',
  letterType: 'TD Benefit Explanation',
  generatedAt: new Date('2026-03-15T12:00:00Z'),
  generatedBy: 'jane.examiner@example.com',
};

// ---------------------------------------------------------------------------
// 1. Document structure
// ---------------------------------------------------------------------------

describe('generateLetterHtml — document structure', () => {
  it('returns a complete HTML document with DOCTYPE', () => {
    const html = generateLetterHtml('Hello world.', METADATA);

    expect(html).toMatch(/^<!DOCTYPE html>/);
    expect(html).toContain('<html');
    expect(html).toContain('<head>');
    expect(html).toContain('<body>');
    expect(html).toContain('</html>');
  });

  it('sets the document title to include claim number and letter type', () => {
    const html = generateLetterHtml('Content.', METADATA);

    expect(html).toContain('WC-2026-0042');
    expect(html).toContain('TD Benefit Explanation');
  });
});

// ---------------------------------------------------------------------------
// 2. Letterhead
// ---------------------------------------------------------------------------

describe('generateLetterHtml — letterhead', () => {
  it('includes Glass Box Solutions company name', () => {
    const html = generateLetterHtml('Content.', METADATA);

    expect(html).toContain('Glass Box Solutions');
  });

  it('includes AdjudiCLAIMS platform branding', () => {
    const html = generateLetterHtml('Content.', METADATA);

    expect(html).toContain('AdjudiCLAIMS');
  });

  it('includes the letterhead CSS class', () => {
    const html = generateLetterHtml('Content.', METADATA);

    expect(html).toContain('class="letterhead"');
  });
});

// ---------------------------------------------------------------------------
// 3. Letter metadata
// ---------------------------------------------------------------------------

describe('generateLetterHtml — metadata block', () => {
  it('includes claim number in the metadata section', () => {
    const html = generateLetterHtml('Content.', METADATA);

    // Should appear at least twice (title + metadata block)
    const matches = html.match(/WC-2026-0042/g) ?? [];
    expect(matches.length).toBeGreaterThanOrEqual(2);
  });

  it('includes letter type in metadata', () => {
    const html = generateLetterHtml('Content.', METADATA);

    expect(html).toContain('TD Benefit Explanation');
  });

  it('includes generatedBy in metadata', () => {
    const html = generateLetterHtml('Content.', METADATA);

    expect(html).toContain('jane.examiner@example.com');
  });

  it('renders the generation date as human-readable text', () => {
    const html = generateLetterHtml('Content.', METADATA);

    // The date 2026-03-15 should appear as formatted text (March 15, 2026)
    expect(html).toContain('2026');
    expect(html).toContain('15');
  });
});

// ---------------------------------------------------------------------------
// 4. UPL disclaimer footer
// ---------------------------------------------------------------------------

describe('generateLetterHtml — UPL disclaimer footer', () => {
  it('includes the UPL disclaimer class', () => {
    const html = generateLetterHtml('Content.', METADATA);

    expect(html).toContain('class="upl-disclaimer"');
  });

  it('disclaimer contains "Not Legal Advice" language', () => {
    const html = generateLetterHtml('Content.', METADATA);

    expect(html).toContain('Not Legal Advice');
  });

  it('disclaimer mentions defense counsel referral requirement', () => {
    const html = generateLetterHtml('Content.', METADATA);

    expect(html).toContain('defense counsel');
  });

  it('includes the generated-by footer line', () => {
    const html = generateLetterHtml('Content.', METADATA);

    expect(html).toContain('class="generated-by"');
    expect(html).toContain('Glass Box Solutions');
  });

  it('footer is inside the letter-footer container', () => {
    const html = generateLetterHtml('Content.', METADATA);

    expect(html).toContain('class="letter-footer"');
  });
});

// ---------------------------------------------------------------------------
// 5. Markdown conversion — headings
// ---------------------------------------------------------------------------

describe('generateLetterHtml — markdown headings', () => {
  it('converts # heading to <h1>', () => {
    const html = generateLetterHtml('# Main Title', METADATA);

    expect(html).toContain('<h1>Main Title</h1>');
  });

  it('converts ## heading to <h2>', () => {
    const html = generateLetterHtml('## Section', METADATA);

    expect(html).toContain('<h2>Section</h2>');
  });

  it('converts ### heading to <h3>', () => {
    const html = generateLetterHtml('### Subsection', METADATA);

    expect(html).toContain('<h3>Subsection</h3>');
  });
});

// ---------------------------------------------------------------------------
// 6. Markdown conversion — inline formatting
// ---------------------------------------------------------------------------

describe('generateLetterHtml — bold and italic', () => {
  it('converts **bold** to <strong>', () => {
    const html = generateLetterHtml('This is **important** text.', METADATA);

    expect(html).toContain('<strong>important</strong>');
  });

  it('converts *italic* to <em>', () => {
    const html = generateLetterHtml('This is *emphasized* text.', METADATA);

    expect(html).toContain('<em>emphasized</em>');
  });

  it('handles bold inside headings', () => {
    const html = generateLetterHtml('## **Bold Heading**', METADATA);

    expect(html).toContain('<h2><strong>Bold Heading</strong></h2>');
  });
});

// ---------------------------------------------------------------------------
// 7. Markdown conversion — lists
// ---------------------------------------------------------------------------

describe('generateLetterHtml — lists', () => {
  it('converts unordered list items to <ul><li>', () => {
    const markdown = '- Item one\n- Item two\n- Item three';
    const html = generateLetterHtml(markdown, METADATA);

    expect(html).toContain('<ul>');
    expect(html).toContain('<li>Item one</li>');
    expect(html).toContain('<li>Item two</li>');
    expect(html).toContain('<li>Item three</li>');
    expect(html).toContain('</ul>');
  });

  it('converts ordered list items to <ol><li>', () => {
    const markdown = '1. First step\n2. Second step\n3. Third step';
    const html = generateLetterHtml(markdown, METADATA);

    expect(html).toContain('<ol>');
    expect(html).toContain('<li>First step</li>');
    expect(html).toContain('<li>Second step</li>');
    expect(html).toContain('</ol>');
  });
});

// ---------------------------------------------------------------------------
// 8. Markdown conversion — tables
// ---------------------------------------------------------------------------

describe('generateLetterHtml — tables', () => {
  it('converts markdown table to HTML table', () => {
    const markdown =
      '| Column A | Column B |\n' +
      '|----------|----------|\n' +
      '| Value 1  | Value 2  |';

    const html = generateLetterHtml(markdown, METADATA);

    expect(html).toContain('<table>');
    expect(html).toContain('<thead>');
    expect(html).toContain('<tbody>');
    expect(html).toContain('<th>Column A</th>');
    expect(html).toContain('<th>Column B</th>');
    expect(html).toContain('<td>Value 1</td>');
    expect(html).toContain('</table>');
  });
});

// ---------------------------------------------------------------------------
// 9. Markdown conversion — horizontal rule
// ---------------------------------------------------------------------------

describe('generateLetterHtml — horizontal rule', () => {
  it('converts --- to <hr>', () => {
    const markdown = 'Before\n\n---\n\nAfter';
    const html = generateLetterHtml(markdown, METADATA);

    expect(html).toContain('<hr>');
  });
});

// ---------------------------------------------------------------------------
// 10. Print CSS
// ---------------------------------------------------------------------------

describe('generateLetterHtml — print CSS', () => {
  it('includes @media print rules', () => {
    const html = generateLetterHtml('Content.', METADATA);

    expect(html).toContain('@media print');
  });

  it('includes @page margin rule', () => {
    const html = generateLetterHtml('Content.', METADATA);

    expect(html).toContain('@page');
  });
});

// ---------------------------------------------------------------------------
// 11. Full letter rendering (integration-style)
// ---------------------------------------------------------------------------

describe('generateLetterHtml — full letter', () => {
  it('renders a realistic letter template without raw placeholders', () => {
    const markdown = `# TD Benefit Rate Explanation

**Date:** 2026-03-15
**Claim Number:** WC-2026-0042

**To:** John Smith
**From:** Pacific Insurance Co.

## Your Temporary Disability Benefit Rate

| Component | Amount |
|-----------|--------|
| AWE | $1,200.00 |
| TD Rate | $800.00 |

Your benefits are payable per **LC 4653**.

## Payment Schedule

- Payments every two weeks per **LC 4650(b)**
- 104-week cap per **LC 4656**

---
*This is a factual explanation. It does not constitute legal advice.*`;

    const html = generateLetterHtml(markdown, METADATA);

    expect(html).toContain('<h1>TD Benefit Rate Explanation</h1>');
    expect(html).toContain('<h2>Your Temporary Disability Benefit Rate</h2>');
    expect(html).toContain('<td>$1,200.00</td>');
    expect(html).toContain('<strong>LC 4653</strong>');
    expect(html).toContain('<li>Payments every two weeks per <strong>LC 4650(b)</strong></li>');
    expect(html).toContain('<hr>');
    expect(html).not.toContain('{{');
    expect(html).not.toContain('}}');
  });

  it('works with empty markdown content', () => {
    const html = generateLetterHtml('', METADATA);

    // Should still produce a valid HTML document with structure
    expect(html).toMatch(/^<!DOCTYPE html>/);
    expect(html).toContain('Glass Box Solutions');
    expect(html).toContain('upl-disclaimer');
  });
});
